/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View_JFrame;

import ToanBo_KhuyenMai.QL_ChiTiet_KhuyenMai_Panel;
import ToanBo_TaiKhoan.QL_TaiKhoan_TatCaPanel;
import ToanBo_TaiKhoan.QL_TaiKhoan_NhanVien_Panel;
import ToanBo_TaiKhoan.QL_TaiKhoan_QuanLy_Panel;
import java.awt.BorderLayout;
import ToanBo_SanPham.QL_SanPham_ChiTiet_Panel;
import javax.swing.JOptionPane;
import ToanBo_BanHang.QL_BanHang_Panel;
import ToanBo_KhachHang.QL_KhachHang_TimKiem_Panel;
import ToanBo_NguyenLieu.QL_ChiTiet_NguyenLieu;
import ToanBo_ThongKe.QL_ThongKe_DoanhThu_Panel;

/**
 *
 * @author ADMIN
 */
public class TrangChu_NQL extends javax.swing.JFrame {
//
//    private TaiKhoan_4_O taiKhoan;
//    public static Tai_Khoan taiKhoan_NQL;
//    QL_Login QL_Log = new QL_Login();

    /**
     * Creates new form TrangChu_NQL
     */
    public TrangChu_NQL() { // TaiKhoan_4_O taiKhoan
//        this.taiKhoan = taiKhoan;
        initComponents();
        this.setLocationRelativeTo(this);
//        hienThiThongTinNguoiDung();
    }

//    private void hienThiThongTinNguoiDung() {
//        String path = taiKhoan.getAnh_TK();
//        if (path == null || path.isEmpty()) {
//            path = "src/images/default.png";
//        }
//
//        ImageIcon icon = new ImageIcon(path);
//        Image img = icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
//        lb_HienThiAnh.setIcon(new ImageIcon(img)); // lblAvatar là JLabel đã đặt trong giao diện
//    }
    public void TatCa_VaiTro() {
        QL_TaiKhoan_TatCaPanel qltk_panel = new QL_TaiKhoan_TatCaPanel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qltk_panel, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }

    public void VaiTro_NhanVien() {
        QL_TaiKhoan_NhanVien_Panel qlnv_Panel = new QL_TaiKhoan_NhanVien_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qlnv_Panel, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }

    public void VaiTro_QuanLy() {
        QL_TaiKhoan_QuanLy_Panel qlql_Panel = new QL_TaiKhoan_QuanLy_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qlql_Panel, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThanhChucNang_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_BanHang = new javax.swing.JButton();
        btn_NguyenLieu = new javax.swing.JButton();
        btn_SanPham = new javax.swing.JButton();
        btn_TaiKhoan = new javax.swing.JButton();
        btn_KhachHang = new javax.swing.JButton();
        btn_ThongKeDoanhThu = new javax.swing.JButton();
        btn_KhuyenMai = new javax.swing.JButton();
        btn_ThongKeDoanhThu1 = new javax.swing.JButton();
        btn_BanHang1 = new javax.swing.JButton();
        TrangChungChuyen = new javax.swing.JPanel();
        lb_DanhMuc = new javax.swing.JLabel();
        CaiDat = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        btn_DangXuat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        lb_HienThiAnh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));

        ThanhChucNang_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Logochinh.jpg"))); // NOI18N

        btn_BanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BanHang.png"))); // NOI18N
        btn_BanHang.setText("Bán Hàng");
        btn_BanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BanHangActionPerformed(evt);
            }
        });

        btn_NguyenLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/NguyenLieu.png"))); // NOI18N
        btn_NguyenLieu.setText("Nhập Hàng");
        btn_NguyenLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NguyenLieuActionPerformed(evt);
            }
        });

        btn_SanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/SanPham.png"))); // NOI18N
        btn_SanPham.setText("Sản Phẩm");
        btn_SanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SanPhamActionPerformed(evt);
            }
        });

        btn_TaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/TaiKhoan.png"))); // NOI18N
        btn_TaiKhoan.setText("Quản Lý Tài Khoản");
        btn_TaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaiKhoanActionPerformed(evt);
            }
        });

        btn_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/KhachHang.png"))); // NOI18N
        btn_KhachHang.setText("Khách Hàng");
        btn_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhachHangActionPerformed(evt);
            }
        });

        btn_ThongKeDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Thong_Ke_Doanh_Thu.png"))); // NOI18N
        btn_ThongKeDoanhThu.setText("Thống Kê Doanh Thu");
        btn_ThongKeDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongKeDoanhThuActionPerformed(evt);
            }
        });

        btn_KhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/KhuyenMai.png"))); // NOI18N
        btn_KhuyenMai.setText("Khuyến Mãi");
        btn_KhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhuyenMaiActionPerformed(evt);
            }
        });

        btn_ThongKeDoanhThu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/History.png"))); // NOI18N
        btn_ThongKeDoanhThu1.setText("Lịch Sử Hoạt Động");
        btn_ThongKeDoanhThu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongKeDoanhThu1ActionPerformed(evt);
            }
        });

        btn_BanHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Ke_Hang.png"))); // NOI18N
        btn_BanHang1.setText("Kệ Hàng");
        btn_BanHang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BanHang1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ThanhChucNang_PanelLayout = new javax.swing.GroupLayout(ThanhChucNang_Panel);
        ThanhChucNang_Panel.setLayout(ThanhChucNang_PanelLayout);
        ThanhChucNang_PanelLayout.setHorizontalGroup(
            ThanhChucNang_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ThanhChucNang_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ThanhChucNang_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_NguyenLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(btn_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ThongKeDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_KhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ThongKeDoanhThu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_BanHang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        ThanhChucNang_PanelLayout.setVerticalGroup(
            ThanhChucNang_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThanhChucNang_PanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_BanHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_NguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_KhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ThongKeDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ThongKeDoanhThu1)
                .addContainerGap())
        );

        TrangChungChuyen.setBackground(new java.awt.Color(255, 255, 255));
        TrangChungChuyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout TrangChungChuyenLayout = new javax.swing.GroupLayout(TrangChungChuyen);
        TrangChungChuyen.setLayout(TrangChungChuyenLayout);
        TrangChungChuyenLayout.setHorizontalGroup(
            TrangChungChuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1128, Short.MAX_VALUE)
        );
        TrangChungChuyenLayout.setVerticalGroup(
            TrangChungChuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lb_DanhMuc.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lb_DanhMuc.setText("Welcome to  Fake AL Fresco’s");

        jButton7.setText("Thông Tin Cá Nhân");

        btn_DangXuat.setText("Đăng Xuất");
        btn_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CaiDatLayout = new javax.swing.GroupLayout(CaiDat);
        CaiDat.setLayout(CaiDatLayout);
        CaiDatLayout.setHorizontalGroup(
            CaiDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CaiDatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CaiDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_DangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        CaiDatLayout.setVerticalGroup(
            CaiDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaiDatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jToggleButton2.setText("Cài Đặt");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tài Khoản"));

        lb_HienThiAnh.setText("null");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_HienThiAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lb_HienThiAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThanhChucNang_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lb_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TrangChungChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(CaiDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ThanhChucNang_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CaiDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lb_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TrangChungChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SanPhamActionPerformed
        // TODO add your handling code here:
        lb_DanhMuc.setText("Quán Lý Sản Phẩm");
        QL_SanPham_ChiTiet_Panel qlspct_Panel = new QL_SanPham_ChiTiet_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qlspct_Panel, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }//GEN-LAST:event_btn_SanPhamActionPerformed

    private void btn_NguyenLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NguyenLieuActionPerformed
        // TODO add your handling code here:
        lb_DanhMuc.setText("Quán Lý Nhập Hàng");
        QL_ChiTiet_NguyenLieu qlnl_Panel = new QL_ChiTiet_NguyenLieu();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qlnl_Panel, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }//GEN-LAST:event_btn_NguyenLieuActionPerformed

    private void btn_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhachHangActionPerformed
        // TODO add your handling code here:
        lb_DanhMuc.setText("Quán Lý Khách Hàng");
        QL_KhachHang_TimKiem_Panel qlkh_Panel = new QL_KhachHang_TimKiem_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qlkh_Panel, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }//GEN-LAST:event_btn_KhachHangActionPerformed

    private void btn_BanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BanHangActionPerformed
        // TODO add your handling code here:
        lb_DanhMuc.setText("Quán Lý Bán Hàng");
        QL_BanHang_Panel qlbh = new QL_BanHang_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qlbh, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }//GEN-LAST:event_btn_BanHangActionPerformed

    private void btn_ThongKeDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongKeDoanhThuActionPerformed
        // TODO add your handling code here:
        lb_DanhMuc.setText("Thống Kê Doanh Thu");
        QL_ThongKe_DoanhThu_Panel tk = new QL_ThongKe_DoanhThu_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(tk, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }//GEN-LAST:event_btn_ThongKeDoanhThuActionPerformed

    private void btn_TaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaiKhoanActionPerformed
        // TODO add your handling code here:
        lb_DanhMuc.setText("Quản Lý Tài Khoản");

        QL_TaiKhoan_TatCaPanel QL_TK = new QL_TaiKhoan_TatCaPanel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(QL_TK, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }//GEN-LAST:event_btn_TaiKhoanActionPerformed

    private void btn_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangXuatActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose(); // đóng giao diện hiện tại
            new Login().setVisible(true); // mở lại form đăng nhập
        }
    }//GEN-LAST:event_btn_DangXuatActionPerformed

    private void btn_KhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhuyenMaiActionPerformed
        // TODO add your handling code here:
        QL_ChiTiet_KhuyenMai_Panel qlkm = new QL_ChiTiet_KhuyenMai_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qlkm, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }//GEN-LAST:event_btn_KhuyenMaiActionPerformed

    private void btn_ThongKeDoanhThu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongKeDoanhThu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThongKeDoanhThu1ActionPerformed

    private void btn_BanHang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BanHang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BanHang1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu_NQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu_NQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu_NQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu_NQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        taiKhoan_NQL = QL_Log.getTaiKhoanTheoEmail(emailDangNhap);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu_NQL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CaiDat;
    private javax.swing.JPanel ThanhChucNang_Panel;
    private javax.swing.JPanel TrangChungChuyen;
    private javax.swing.JButton btn_BanHang;
    private javax.swing.JButton btn_BanHang1;
    private javax.swing.JButton btn_DangXuat;
    private javax.swing.JButton btn_KhachHang;
    private javax.swing.JButton btn_KhuyenMai;
    private javax.swing.JButton btn_NguyenLieu;
    private javax.swing.JButton btn_SanPham;
    private javax.swing.JButton btn_TaiKhoan;
    private javax.swing.JButton btn_ThongKeDoanhThu;
    private javax.swing.JButton btn_ThongKeDoanhThu1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lb_DanhMuc;
    private javax.swing.JLabel lb_HienThiAnh;
    // End of variables declaration//GEN-END:variables
}
