/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View_JPanel;

import java.awt.BorderLayout;

/**
 *
 * @author ADMIN
 */
public class ChucNang_PhuDoanhThu extends QL_ThongKe_DoanhThu_Panel{

    /**
     * Creates new form ChucNang_PhuDoanhThu
     */
    public ChucNang_PhuDoanhThu(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_SanPhamBanChay2 = new javax.swing.JButton();
        btn_DoanhThu2 = new javax.swing.JButton();

        btn_SanPhamBanChay2.setText("Sản Phẩm Bán Chạy");
        btn_SanPhamBanChay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SanPhamBanChay2ActionPerformed(evt);
            }
        });

        btn_DoanhThu2.setText("Doanh Thu");
        btn_DoanhThu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoanhThu2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_DoanhThu2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_SanPhamBanChay2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DoanhThu2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SanPhamBanChay2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DoanhThu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoanhThu2ActionPerformed
        // TODO add your handling code here:
        ThongKe_ChucNangDoanhThu_Panel cnthdh_panel = new ThongKe_ChucNangDoanhThu_Panel();
        Trang_Chung_Chuyen.removeAll();
        Trang_Chung_Chuyen.setLayout(new BorderLayout());
        Trang_Chung_Chuyen.add(cnthdh_panel, BorderLayout.CENTER);
        Trang_Chung_Chuyen.revalidate();
        Trang_Chung_Chuyen.repaint();
    }//GEN-LAST:event_btn_DoanhThu2ActionPerformed

    private void btn_SanPhamBanChay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SanPhamBanChay2ActionPerformed
        // TODO add your handling code here:
        ThongKe_SanPhamBanChay_Panel cnspbc_panel = new ThongKe_SanPhamBanChay_Panel();
        Trang_Chung_Chuyen.removeAll();
        Trang_Chung_Chuyen.setLayout(new BorderLayout());
        Trang_Chung_Chuyen.add(cnspbc_panel, BorderLayout.CENTER);
        Trang_Chung_Chuyen.revalidate();
        Trang_Chung_Chuyen.repaint();
    }//GEN-LAST:event_btn_SanPhamBanChay2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Trang_Chung_Chuyen;
    private javax.swing.JPanel Trang_Chung_Chuyen1;
    private javax.swing.JButton btn_DoanhThu;
    private javax.swing.JButton btn_DoanhThu1;
    private javax.swing.JButton btn_DoanhThu2;
    private javax.swing.JButton btn_SanPhamBanChay;
    private javax.swing.JButton btn_SanPhamBanChay1;
    private javax.swing.JButton btn_SanPhamBanChay2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
