/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View_JPanel;

/**
 *
 * @author ADMIN
 */
public class QL_TaiKhoan_CNP_Panel extends QL_TaiKhoan_TatCaPanel {

    /**
     * Creates new form QL_TaiKhoan_CNP_Panel
     */
    public QL_TaiKhoan_CNP_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_FilltoTatCa = new javax.swing.JButton();
        btn_FilltoNhanVien = new javax.swing.JButton();
        btn_FilltoQuanLy = new javax.swing.JButton();

        btn_FilltoTatCa.setText("Tất Cả");
        btn_FilltoTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FilltoTatCaActionPerformed(evt);
            }
        });

        btn_FilltoNhanVien.setText("Nhân Viên");
        btn_FilltoNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FilltoNhanVienActionPerformed(evt);
            }
        });

        btn_FilltoQuanLy.setText("Quản Lý");
        btn_FilltoQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FilltoQuanLyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_FilltoTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_FilltoNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_FilltoQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_FilltoTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_FilltoNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_FilltoQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_FilltoNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FilltoNhanVienActionPerformed
        // TODO add your handling code here:
        String VaiTro = "Nhân Viên";
        FillToTableTheoVaiTro(VaiTro);
    }//GEN-LAST:event_btn_FilltoNhanVienActionPerformed

    private void btn_FilltoTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FilltoTatCaActionPerformed
        // TODO add your handling code here:
        FillToTable();
    }//GEN-LAST:event_btn_FilltoTatCaActionPerformed

    private void btn_FilltoQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FilltoQuanLyActionPerformed
        // TODO add your handling code here:
        String VaiTro = "Quản Lý";
        FillToTableTheoVaiTro(VaiTro);
    }//GEN-LAST:event_btn_FilltoQuanLyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_FilltoNhanVien;
    private javax.swing.JButton btn_FilltoQuanLy;
    private javax.swing.JButton btn_FilltoTatCa;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
